/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mdascalc;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class MdasCalculator extends javax.swing.JFrame {

    /**
     * Creates new form MdasCalculator
     */
    public MdasCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        firstNum = new javax.swing.JLabel();
        secondNum = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        btn_Validate = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        rb_Subtraction = new javax.swing.JRadioButton();
        rb_Multiplication = new javax.swing.JRadioButton();
        rb_Addition = new javax.swing.JRadioButton();
        rb_Division = new javax.swing.JRadioButton();
        tf_firstNum = new javax.swing.JTextField();
        tf_secondNum = new javax.swing.JTextField();
        tf_result = new javax.swing.JTextField();
        rb_Modulus = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select option", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setToolTipText("ArithmeticFunction");

        firstNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        firstNum.setText("Enter first number: ");

        secondNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        secondNum.setText("Enter second number: ");

        result.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        result.setText("Show result");

        btn_Validate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Validate.setText("Validate");
        btn_Validate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ValidateActionPerformed(evt);
            }
        });

        btn_Reset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Reset.setText("Reset");
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });

        btn_Exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Exit.setText("Exit");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_Subtraction);
        rb_Subtraction.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rb_Subtraction.setText("Subtraction");

        buttonGroup1.add(rb_Multiplication);
        rb_Multiplication.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rb_Multiplication.setText("Multiplication");

        buttonGroup1.add(rb_Addition);
        rb_Addition.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rb_Addition.setText("Addition");

        buttonGroup1.add(rb_Division);
        rb_Division.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rb_Division.setText("Division");

        tf_firstNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tf_secondNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tf_result.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        buttonGroup1.add(rb_Modulus);
        rb_Modulus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rb_Modulus.setText("Modulus");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btn_Validate)
                        .addGap(131, 131, 131)
                        .addComponent(btn_Reset))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(secondNum)
                            .addComponent(firstNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(result, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_secondNum)
                            .addComponent(tf_firstNum)
                            .addComponent(tf_result, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_Multiplication)
                    .addComponent(rb_Subtraction)
                    .addComponent(btn_Exit)
                    .addComponent(rb_Addition)
                    .addComponent(rb_Division)
                    .addComponent(rb_Modulus))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_firstNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNum))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(secondNum)
                            .addComponent(tf_secondNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(result)
                            .addComponent(tf_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(rb_Addition)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Subtraction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Multiplication)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Division)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Modulus)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Validate)
                    .addComponent(btn_Reset)
                    .addComponent(btn_Exit))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        tf_firstNum.setText("");
        tf_secondNum.setText("");
        tf_result.setText("");
        
        tf_firstNum.requestFocus();
        
    }//GEN-LAST:event_btn_ResetActionPerformed

    private void btn_ValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ValidateActionPerformed
        try{
            double num1 = Double.parseDouble(tf_firstNum.getText());
            double num2 = Double.parseDouble(tf_secondNum.getText());
            double num3;
            
            if(!(rb_Addition.isSelected())&&!(rb_Subtraction.isSelected())&&!(rb_Multiplication.isSelected())&&!(rb_Division.isSelected())&&!(rb_Modulus.isSelected())){
                JOptionPane.showMessageDialog(null, "Select an option now!", "See radio buttons ", JOptionPane.INFORMATION_MESSAGE);
            }
                if(rb_Addition.isSelected()){
                    num3 = (num1 + num2);
                    String total = String.format("%.0f", num3);
                   tf_result.setText(total);
                }
                
               if(rb_Subtraction.isSelected()){
                    num3 = (num1 - num2);
                    String total = String.format("%.0f", num3);
                    tf_result.setText(total);
                }
               
              if(rb_Multiplication.isSelected()){
                    num3 = (num1 * num2);
                    String total = String.format("%.0f", num3);
                    tf_result.setText(total);
                }
              
               if(rb_Division.isSelected()){
                    num3 = (num1 / num2);
                    String total = String.format("%.0f", num3);
                    tf_result.setText(total);
                }
               
                if(rb_Modulus.isSelected()){
                    num3 = (num1 % num2);
                    String total = String.format("%.0f", num3);
                    tf_result.setText(total);
                }
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Enter a valid number", "Only numbers are allowed", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_ValidateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MdasCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MdasCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MdasCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MdasCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MdasCalculator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_Validate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel firstNum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rb_Addition;
    private javax.swing.JRadioButton rb_Division;
    private javax.swing.JRadioButton rb_Modulus;
    private javax.swing.JRadioButton rb_Multiplication;
    private javax.swing.JRadioButton rb_Subtraction;
    private javax.swing.JLabel result;
    private javax.swing.JLabel secondNum;
    private javax.swing.JTextField tf_firstNum;
    private javax.swing.JTextField tf_result;
    private javax.swing.JTextField tf_secondNum;
    // End of variables declaration//GEN-END:variables
}
